# Generated by Django 5.1.1 on 2025-10-29 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sin_leer', 'Sin leer'), ('leido', 'Leído'), ('eliminado', 'Eliminado')], default='sin_leer', max_length=20)),
                ('type', models.CharField(choices=[('sistema', 'Sistema'), ('alerta', 'Alerta'), ('mensaje', 'Mensaje'), ('personalizada', 'Personalizada')], default='sistema', max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('action_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
